name: test
on: [push, pull_request]
jobs:

  test:
    name: test
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: test
      run: go test ./...
